one = "All "
two = "work "
three = "and "
four = "no "
five = "play "
six = "makes "
seven = "Jack "
eight = "a "
nine = "dull "
ten = "boy"
eleven = "."
print( one + two + three + four + five + six + seven + eight + nine + ten + eleven)
